create_clock -period 10.000 -name Clock -waveform {0.000 5.000} [get_ports Clock]
create_generated_clock -name Clk_deb -source [get_ports Clock] -divide_by 262144 [get_pins {schematic_i/divider_0/U0/JK1[17].ST2/QIN_reg/Q}]
create_generated_clock -name Clk_led -source [get_ports Clock] -divide_by 524288 [get_pins {schematic_i/divider_0/U0/JK1[18].ST2/QIN_reg/Q}]

create_generated_clock -name schematic_i/debounce_0/U0/Q3 -source [get_pins {schematic_i/divider_0/U0/JK1[17].ST2/QIN_reg/Q}] -divide_by 1 [get_pins schematic_i/debounce_0/U0/Q3_reg/Q]
set_property IOSTANDARD LVCMOS33 [get_ports Clock]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports D_IN]
set_property IOSTANDARD LVCMOS33 [get_ports updown]
set_property PACKAGE_PIN E3 [get_ports Clock]
set_property PACKAGE_PIN E16 [get_ports RESET]
set_property PACKAGE_PIN N6 [get_ports {Anode[0]}]
set_property PACKAGE_PIN M6 [get_ports {Anode[1]}]
set_property PACKAGE_PIN M3 [get_ports {Anode[2]}]
set_property PACKAGE_PIN N5 [get_ports {Anode[3]}]
set_property PACKAGE_PIN L3 [get_ports {LED[0]}]
set_property PACKAGE_PIN N1 [get_ports {LED[1]}]
set_property PACKAGE_PIN L5 [get_ports {LED[2]}]
set_property PACKAGE_PIN L4 [get_ports {LED[3]}]
set_property PACKAGE_PIN K3 [get_ports {LED[4]}]
set_property PACKAGE_PIN M2 [get_ports {LED[5]}]
set_property PACKAGE_PIN L6 [get_ports {LED[6]}]
set_property PACKAGE_PIN T16 [get_ports D_IN]
set_property PACKAGE_PIN U9 [get_ports updown]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]



